<div style="background: #000;
            color: #FFF;
            margin: 0px;
                padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1 style="padding: 2220px 210px -30px 0px;">Week 14 Lab</h1>
</div>

In [1]:
# imports

import numpy as np

## Exercise 1

Create the following numpy arrays:
    
a) An array using the following lists (make it interesting if you can)

In [14]:
l = [0,0,0,0,0] 
m = [1,2,3,4,5]

a = np.array(l)
print(a)
b = np.array(m)
print(m)

#concatenating
d = np.concatenate((l,m), axis=0)
d

[0 0 0 0 0]
[1, 2, 3, 4, 5]


array([0, 0, 0, 0, 0, 1, 2, 3, 4, 5])

b) A 3 x 4 matrix of zeros: 

In [46]:
c = np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

c) A 2 x 4 matrix of zeros and ones of the following format:

[[0,0,1,1], [0,0,1,1]]

(try without using python lists)

In [36]:
g = ([0,0,1,1], [0,0,1,1])
e = np.array(g)
e


array([[0, 0, 1, 1],
       [0, 0, 1, 1]])

e) A 3 x 4 array from the following numpy array (do not change the already existing code):

In [40]:
r = np.arange(0,12)
# enter your code below
r
s = r.reshape(3,4)
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

f) A 1 x 13 array from the following array

look into the `resize` method

In [47]:
n = np.empty(shape=(2,6))

### enter your code below
n.resize(1,13)
n

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

) using the following array, create an array that consists of the same numbers but squared and in order from smallest to largest

In [53]:
n = np.array([7, 6, 9, 5, 8, 9, 6, 10, 3, 4, 3, 3, 1, 2, 5, 8, 6, 1, 6, 0])
### enter your code below
m = n*2
m.sort()
m

array([ 0,  2,  2,  4,  6,  6,  6,  8, 10, 10, 12, 12, 12, 12, 14, 16, 16,
       18, 18, 20])

## Exercise 2

Produce  the array as asked

a) Create a 3x3x3 array with the numbers from 1, 27. Then slice it to produce the 3x3 array in the middle.

In [64]:
h = np.arange(1,28)
h.resize(3,3,3)
h
h[1,:,:]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

b) Create a 3 x 3 array of random numbers. Then slice it to produce the numbers in the 2-index column.

In [76]:
rng = np.random.default_rng(0)
### enter your code below 
r = rng.random((3, 3))
print(r)
r[2]

[[0.63696169 0.26978671 0.04097352]
 [0.01652764 0.81327024 0.91275558]
 [0.60663578 0.72949656 0.54362499]]


array([0.60663578, 0.72949656, 0.54362499])

c) Create a 3x3x3 array of zeros. Slice a 2x2 array from it and change the values to 1s. Then output the original 3x3x3 with `0`'s and `1`s

In [95]:
t = np.zeros((3,3,3))
t
s = t[0, :2, :2]
s
s[::] =1
s
t

array([[[1., 1., 0.],
        [1., 1., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

d) Create an array of all the numbers from 1, 27 (inclusive). Then produce a slice that outputs only the even numbers less than 14.

In [155]:
q = np.arange(1,28)
q

q[(q<14) & (q%2==0)]


# for i in q:
#     if i < 14 and i%2 == 0:
#         print(i)
        
# type(i)

array([ 2,  4,  6,  8, 10, 12])

## Exercise 3

a) Create an array of all postive integers from 1 to 100.    
b) Reshape it into a 10 x 10 matrix  
c) Remove multiples (so numbers that aren't prime  
d) Output the prime numbers.  

a)

In [115]:
y = np.arange(1,101)
y

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

b) reshape it into a 10 x 10 matrix

In [121]:
x = y.reshape(10,10)
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

c) starting with 2 (until you get to sqrt(100) or 10), replace multiples of that number with 0

In [218]:
x[(x!=2) & (x%2==0)] = 0
x

x[(x!=3) & (x%3==0)] =0
x

x[(x!=5) & (x%5==0)] = 0
x

x[(x!=7) & (x%7==0)] = 0
x


array([[ 1,  2,  3,  0,  5,  0,  7,  0,  0,  0],
       [11,  0, 13,  0,  0,  0, 17,  0, 19,  0],
       [ 0,  0, 23,  0,  0,  0,  0,  0, 29,  0],
       [31,  0,  0,  0,  0,  0, 37,  0,  0,  0],
       [41,  0, 43,  0,  0,  0, 47,  0,  0,  0],
       [ 0,  0, 53,  0,  0,  0,  0,  0, 59,  0],
       [61,  0,  0,  0,  0,  0, 67,  0,  0,  0],
       [71,  0, 73,  0,  0,  0,  0,  0, 79,  0],
       [ 0,  0, 83,  0,  0,  0,  0,  0, 89,  0],
       [ 0,  0,  0,  0,  0,  0, 97,  0,  0,  0]])

d) Using a slice, output your prime sieve containing all of the prime numbers less than 0 (be sure to exclude 1 from your slice)

hint: the length of such slice should be `25`

In [227]:
prime = np.unique(x)[2:]
print(prime)
len(prime)

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


25