<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1>Phase 2 Practice Assessment</h1>
</div>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Multiple Choice Questions 

**[5% each; 25% total]**

**1. What is a main benefit of test-driven development?**

**a.** Less money needed  
**b.** More fun   
**c.** Slower development  
**d.** Fewer bugs to deal with  

**2. What would we use to calculate the number of ways we could arrange 20 students into a 5 person committee if we didn't care about committees having the same 5 members?**

**a.** Factorial  
**b.** Permutation  
**c.** Combination  
**d.** Probability Mass Function  

**3. What is the set of possible outcomes for a random variable called?**

**a.** Event Space  
**b.** Experiment    
**c.** Sample Space   
**d.** Probability Distribution  

**4. Multiplying a matrix by its inverse results in what type of matrix**

**a.** Square Matrix  
**b.** The Matrix Trilogy  
**c.** Zero Matrix  
**d.** Identity Matrix  

**5. What's a consequence of underfitting?**

**a.** Incorrect predictions   
**b.** High bias  
**c.** Getting fired    
**d.** High variance  

# Python 

**[5% each; 25% total]** 


**1. Implement a binary tree in a python class that has the four methods we've covered.**

In [1]:
class BinaryTree:
    def __init__(self, data):
        self.left = None
        self.right = None
        self.data = data
        
    def insert(self, data):
        if self.data:
            if data < self.data:
                if self.left is None:
                    self.left = BinaryTree(data)
                else:
                    self.left.insert(data)
            elif data > self.data:
                if self.right is None:
                    self.right = BinaryTree(data)
                else:
                    self.right.insert(data)
            else:
                print("duplicate, cannot be added")
        else:
            self.data = data
            
    def find(self, val):
        if val < self.data:
            if self.left is None:
                return f"{val} not found"
            return self.left.find(val)
        elif val > self.data:
            if self.right is None:
                return f"{val} not found"
            return self.right.find(val)
        else:
            return f"{val} found"
            
    def print(self):
        if self.left:
            self.left.print()
        print(self.data)
        if self.right:
            self.right.print()
            
tree = BinaryTree(12)
tree.insert(6)
tree.insert(2)
tree.insert(3)
tree.insert(8)
tree.insert(7)
tree.insert(9)
tree.insert(16)
tree.insert(13)
tree.insert(15)
tree.insert(20)

tree.print()

2
3
6
7
8
9
12
13
15
16
20


**2. Create a generator function that yields a power of 2 every time it's used. Demonstrate that it works.**

In [10]:
my_list = [1, 3, 6, 10]

In [11]:
def generator(my_list):

    a = (x**2 for x in my_list)


In [13]:
next(a)

36

**3. Convert the numbers 718 and 917 into binary values and then XOR them.**

In [17]:
a = bin(718)
print(a)
b = bin(917)
print(b)
print(type(b))

0b1011001110
0b1110010101
<class 'str'>


In [19]:
c = ''.join('0' if i == j else '1' for i, j in zip(a,b))  #they are  the same lenght so it'll work
print(c)

000101011011


**4. Create a dataclass that has the following attributes: name, age, grade and course.**

In [7]:
from dataclasses import dataclass

#No need for an init method
@dataclass
class Data:
    name: str  #must use type annotations 
    age: int
    grade: int 
    course: str
    

In [8]:
a = Data("Jane", 15, 8, "math")
print(a.name)
print(a)

Jane
Data(name='Jane', age=15, grade=8, course='math')


**5. Convert the following formula into a python function. Then use it to calculate the the standard deviation of the list.**

$$ \sigma = \sqrt{\frac{1}{N}\sum_{i=1}^{N}(x_i - \mu)^{2}}$$

In [34]:
l = [10, 12, 23, 23, 16, 23, 21, 16]


In [35]:
def stand_dev(l):
    mu = sum(i for i in l)/len(l)
    s = ((1/N * sum((x[i]-mu)**2))**0.5) for i in l
    return s

# Machine Learning Questions 

**1. Why would we not want a macine learning model to perfectly fit the data we used to train it?**

**2. What assumption must we make in order to do a linear regressions? Why do we make this assumption?**

**3. Explain what variance is and why increasing the complexity of our model causes it. What sacrifice might we make by lowering the complexity of our model?**

# Numpy

**This section is worth 12.5%**

**1. Create an array of array of numbers from 1 to 100. Then use that array to get the results of the following formula for all of those values.**

$$ y = x^{2}-x-6$$

In [11]:
import numpy as np

a = np.arange(1,101)
a
for i in a:
    y = i**2 -i - 6
    print(y)

-6
-4
0
6
14
24
36
50
66
84
104
126
150
176
204
234
266
300
336
374
414
456
500
546
594
644
696
750
806
864
924
986
1050
1116
1184
1254
1326
1400
1476
1554
1634
1716
1800
1886
1974
2064
2156
2250
2346
2444
2544
2646
2750
2856
2964
3074
3186
3300
3416
3534
3654
3776
3900
4026
4154
4284
4416
4550
4686
4824
4964
5106
5250
5396
5544
5694
5846
6000
6156
6314
6474
6636
6800
6966
7134
7304
7476
7650
7826
8004
8184
8366
8550
8736
8924
9114
9306
9500
9696
9894


**2. Create two arrays containing the following matrices. Then prove they are inverses.**

$$ A = \begin{bmatrix}
5&2\\
-7&-3\\
\end{bmatrix}$$

$$ B = \begin{bmatrix}
3&2\\
-7&-5\\
\end{bmatrix}$$

In [27]:
a=np.array([[5,2],[-7,-3]])
b=np.array([[3,2],[-7, -5]])
print(a)
print(b)

[[ 5  2]
 [-7 -3]]
[[ 3  2]
 [-7 -5]]


In [32]:
ainv = np.linalg.inv(a)  #the inverse of a
print(ainv) #we see that the invrse of a looks like b

[[ 3.  2.]
 [-7. -5.]]


**3. Create an array using the following matrix so we have the values from the odd rows of the even columns.**

Odd rows meaning rows with odd indices. Even columns meaning columns with even indices.

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[15,16,17,18,19,20,21]])
a

**4. Create a square matrix containing the first 9 values of the following function. Reverse it and then flatten it. Show all of your code.**

$$ y = |x|$$


**5. Create a sqaure numpy array of random numbers. Sort the array and then concatenate it with a similar sized matrix of zeros. Then compute the mean. Show all work.**

# Pandas 

**This section is worth 12.5%**

The questions for this section use the dataframe below:

In [ ]:
df = pd.DataFrame([
["alice", 9, 50, np.nan,75],
["bob", 5, 75, np.nan, 65],
["carol", 8, 90, np.nan, 90],
["dave", 8, 85, 90, 85],
["erica", 9, 95, 100, 95],
["frank", 0, 30, 60, 30],
["gina", 10,85, 100, np.nan],
["hector", 10, 95, np.nan, 95],
["ivan", 9,85, 90, np.nan],
["john", 5,70, 80, np.nan]
], columns=['student', 'hws completed', 'test average', 'project grade', 'final score'])

df

**1. Fix the `"hws completed"` column by turning the number of hws completed into a percentage. There were 10 hws in the semester and students got 100% on each hw they completed.**

**2. Fix the missing values in the column `"project grade"` using the following formula**.

$$ \textbf{final grade} = \frac{\textbf{hw grade} + \textbf{test grade} + \textbf{project grade}}{3} $$

**3. Fix the missing values in the column `"final grade"` using the formula from the previous exercise.**

**4. Filter our dataframe and output the top 3 students by final grade.**

**5. Calculate the average grade for each of our four columns.**

# SQL 

Carol just received a job offer for a position as data scientist paying \$140,000. Given the following sql database, update her information to reflect this new position.

In [16]:
# run this cell to set up your sqlite3 db.
import sqlite3

sql_commands = \
"""
DROP TABLE IF EXISTS employees;

CREATE TABLE employees (
 id INTEGER PRIMARY KEY,
 name TEXT NOT NULL,
 position TEXT NOT NULL,
 salary INTEGER NOT NULL
);

INSERT INTO employees 
(name, position, salary)
VALUES 
('Alice', 'software engineer', 120000),
('Bob', 'web developer',  80000),
('Carol', 'intern', 10000);
"""

db = sqlite3.connect('employees.db')
cursor = db.cursor()
cursor.executescript(sql_commands)
db.commit()
db.close()

In [17]:
# use this function for your answers.
def with_conn(statement):
    conn = sqlite3.connect('employees.db')
    with conn:
        cur = conn.cursor()
        cur.execute(statement)
        result = cur.fetchall()
        return result 

In [18]:
with_conn("SELECT * FROM employees;")

[(1, 'Alice', 'software engineer', 120000),
 (2, 'Bob', 'web developer', 80000),
 (3, 'Carol', 'intern', 10000)]

In [23]:
with_conn('UPDATE employees SET position="data scientist", salary=140000 WHERE id = 3;')

[]

In [24]:
with_conn("SELECT * FROM employees;")

[(1, 'Alice', 'software engineer', 120000),
 (2, 'Bob', 'web developer', 80000),
 (3, 'Carol', 'data scientist', 140000)]

# Matplotlib 
**This section is worth 5%**

Using the following dataset, create a chart of the data using the right chart to convey the information. Make sure your chart is professional looking, utilizing axis labeling and a proper title. 

In [ ]:
df = pd.DataFrame([['alice',3.4,2016, '1LdRcdxfbSnmCYYNdeYpUnztiYzVfBEQeC'],['bob',0.4555, 2018,'12ib7dApVFvg82TXKycWBNpN8kFyiAN1dr'], ['carol', 5.42482302, 2015, '1LdRcdxfbSnmCYYNdeYpUnztiYzVfBEQeC'], ['davin',20.25, 2013,'3ETUmNhL2JuCFFVNSpk8Bqx2eorxyP9FVh'], ['eric',0.05,2021, '1LdRcdxfbSnmCYYNdeYpUnztiYzVfBEQeC']], columns=['name', 'bitcoins', 'year started', 'public key'])
df.head()